#! /user/bin/env python
import random
lowercase_letters = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'] 
uppercase_letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z']
numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
# symbols = ['!', '#', '$', '%', '&', '(', ')', '*', '+']

nr_letters = int(input("How many lowercase letters would you like?\n"))
nr_uletters = int(input("How many uppercase letters would you like?\n"))
nr_numbers = int(input("How many numbers would you like?\n"))

#symbols left optional for simplicity
# nr_symbols = int(input(f"How many symbols would you like?\n"))

password_list = []

for char in range(1, nr_letters + 1):
  password_list.append(random.choice(lowercase_letters))

for char in range(1, nr_numbers + 1):
  password_list.append(random.choice(numbers))

for char in range(1, nr_uletters + 1):
  password_list.append(random.choice(uppercase_letters))
  
# for char in range(1, nr_symbols + 1):
#  password_list.append(random.choice(symbols))
  
random.shuffle(password_list)

password = ""
for char in password_list:
  password += char

print(f"Your password is: {password}")
